language: scala
scala:
- 2.10.4
- 2.11.6
jdk:
- oraclejdk7
- oraclejdk8
script:
- echo "Running Readme"; sbt readme/run; echo "Running Compile"; sbt ++$TRAVIS_SCALA_VERSION modules/compile; echo "Running Tests"; sbt ++$TRAVIS_SCALA_VERSION modules/test
sudo: false
